package com.pioneer.nycfirewire.utils

object Constants {
    var CODE_SUCCESS= "success"
    var CODE_UPDATED= "updated"
    var INCIDENT_ID="incident_id"
    var LOCALITY_DATA="locality"
    var LOCALITY_NAME="locality_name"
    var GOOGLE="google"
    var FACEBOOK="facebook"
    var SUB_PRODUCT_ID="monthly"
   // var SUB_PRODUCT_ID="test"
    var LOC_IDS="locality_ids"
    var SUB_LOC_IDS="sub_loc_ids"
    var TYPE_NOTIFICATION="notification"
    var TYPE_AREA="area"
    var FROM_START="from_start"
    var PROFILE_UPDATED="profile_updated"
    var INVALID_OTP="invalid_otp"
    var PLAY_STORE_URL="https://play.google.com/store/search?q=nyc+fire+wire+app&c=apps&hl=es_419"

    // Legacy roles from the removed Gettin' Salty feature. Unused in code —
    // the premium gate is a denylist on basic_user — but ~73 production
    // accounts still carry them, so they are kept here as documentation.
    var USER_MONTHLY="gettinsalty_monthly"
    var USER_YEARLY="gettinsalty_yearly"
    var USER_PREMIUM_FREE="premium_free"
    var USER_BASIC_USER="basic_user"
    var USER_SUB_ADMIN="sub_admin"
    var USER_SUPER="super"
    var USER_ADMIN="admin"
    var AUDIO_BROADCAST="com.pioneer.nycfirewire.ACTION_SERVICE_STOPPED"
    var LIGHT="light"
    var DARK="dark"
    var ACTION_STOP="action_stop"
    var EMAIL_ID="email_id"


    //Analytics page names
    var COMMENTS_FRAGMENT="comments"
    var FEED_FILTER_FRAGMENT="FeedAreas"
    var FILTER_FRAGMENT="SelectAreas"
    var NEWS_FRAGMENT="news_feed"
    var WIRE_FRAGMENT="incident_feed"
    var BOTTOM_SHEET_FRAGMENT="Photo selection"
    var RADIO_FEED="scanner_feeds"
    var FORGOT_PASSWORD="Forgot Password"
    var LOGIN="Login Page"
    var MAP_PAGE="Map Page"
    var MY_ACCOUNT="Payment Page"
    var MENU="main_menu"
    var NEWS_DETAIL="News Detail"
    var NOTIFICATION_AREAS="Notification Areas"
    var PERSONALIZATION="Personalization"
    var REGISTRATION="Register User"
    var SELECT_AREA="Select Area"
    var PROFILE_UPDATE="Update Profile"
    var INCIDENT_POST="Incident Post"
    var INCIDENT_DETAILS="incident_details"
    var RADIO_CLICKED="radio_clicked"
    var CODE_EMAIL_NOT_VERIFIED="email_not_verified"
    var FROM_PAGE="from_page"
}